### ISSUE TITLE
TPM not working

### ISSUE THREAD

**Issue by pdidi2013** [Seeed-Studio/AzureGroveKit#2]
When deploying AzureGroveKit to a Raspberry PI 3 with Windows 10 IoT Core version 10.0.16299.309 I keep getting the following error after clicking Run:

Please fill Device ConnectString (From Azure) on TPM

Though TPM has been setup as Software TPM Emulator(NoSecurity) using a correct ConnectString from Azure IoT Hub (this string was succesfully used with the default Windows 10 Quick-Run example Azure IoT Hub example)

**Comment by dmitriyteteruk** [comment]
Same issue on 10.0.17134.1 build "Please fill Device ConnectString (From Azure) on TPM" error.

**Comment by daxternl** [comment]
Same issue here!

**Comment by nacestruc** [comment]
Same issue here also - the error that is printed out is 

> "Sorry... Please fill Device ConnectionString (From Azure) on TPM. Contact us for help."

I would kindly ask you for your help. What to do? Azure IoT HUB connection string has been already assigned.

**Comment by daxternl** [comment]
I was able to fix the issue; it seems like the compiled package hasn't got enough _Capabilities_ defined while packaging. Therefor, it can't access the TPM settings. I've loaded the source code in visual studio,  re-packaged the solution and added the following capabilities to make it work: Internet (client & server), Shared User Certificates & User Account Information. Gook luck!

**Comment by nacestruc** [comment]
Dear GhandiHarder! Thank you very much. For the source code currently published, this is the correct solution. For anyone else facing the same issue. Open Package.appxmanifest inside Visual Studio, navigate to Capabilities tab and make sure that the following checkboxes are marked: Internet (Client), Shared User Certificates, User Account Information. After that just create app package and install it into your device.

**Comment by dmitriyteteruk** [comment]
Dear  @GhandiHarder , can you please update files here on GitHub? As source code and generated App still works incorrect. Changing Package.appxmanifest inside Visual Studio is OK for me, but during creatin package process I got 7 errors. 
``Severity	Code	Description	Project	File	Line	Suppression State
Error		at SerializationAssemblyGenerator.Program.Main(String[] args)	AzureGroveKit			
Error		at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelper(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, GeneratorSettings settings, String intermediateAssembly, IEnumerable`1 wcfSerializers)	AzureGroveKit			
Error		at SerializationAssemblyGenerator.Program.AddKnownContractsLists(McgCodeTypeDeclaration container, ContractTables tables)	AzureGroveKit			
Error		System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.	AzureGroveKit			
Error		at System.Collections.Generic.Dictionary`2.get_Item(TKey key)	AzureGroveKit			
Error		at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelperCode(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, IEnumerable`1 wcfSerializers)	AzureGroveKit			
Error		ILT0032: Failed to compile serialization code. See the build log for error details.	AzureGroveKit``

**Comment by KillingJacky** [comment]
Guys, sorry for bringing inconveniences, the update of Windows 10 IoT Core has broken the codes, we're working on fixing this.

**Comment by dmitriyteteruk** [comment]
> Guys, sorry for bringing inconveniences, the update of Windows 10 IoT Core has broken the codes, we're working on fixing this.

@KillingJacky while you are fixing the code can you advise what version of Windows 10 IoT you did test code before?

**Comment by nacestruc** [comment]
You should clone the whole repository and build it for ARM (Visual Studio 2k17). Meanwhile change the following (as @GhandiHarder already wrote down):

> "Open Package.appxmanifest inside Visual Studio, navigate to Capabilities tab and make sure that the following checkboxes are marked: Internet (Client), Shared User Certificates, User Account Information. After that just create app package and install it into your device."

Please report if the following steps will resolve your issue.

**Comment by dmitriyteteruk** [comment]
@nacestruc , I have tried to do it, but during packaging I am getting errors - I mentioned it in above message. If you fixed it - can you upload it here?

**Comment by nacestruc** [comment]
Which version of Visual Studio are you using - 2k17?

**Comment by dmitriyteteruk** [comment]
2017.

**Comment by KillingJacky** [comment]
@dmitriyteteruk I'll adapt all the instructions to version 10.0.17134

**Comment by KillingJacky** [comment]
@dmitriyteteruk The errors are caused by compiling with .NET native tool chain, and it seem there's no quick solution. So we just disabled `Compile with .NET native tool chain`, and let's wait the NuGet packages and the native tool chain fit better to clear the errors.
I've just re-packed the App, more testings and the updated instructions are on the way. I'm still worrying that the Windows 10 update broke more things, so any crash / bug report is welcomed!

**Comment by dmitriyteteruk** [comment]
@KillingJacky can you then advise with which build of Win 10 IoT current code works fine? I have below FFU for RPi3:
- 14393.67.160804-2231.rs1
- 16299.15.170928-1534.rs3
- 17134.1.180410-1804.rs4 - does not work

**Comment by KillingJacky** [comment]
What do you mean "does not work"?

**Comment by dmitriyteteruk** [comment]
TPM with code 1.0.7.0 version. I did check 1.0.8.0 now with 17134 and it works fine! Thank you very much for you help!
