### ISSUE TITLE
Is there source code for the lib?

### ISSUE THREAD

**Issue by djaus2** [Seeed-Studio/AzureGroveKit#4]

**Comment by awong1900** [comment]
Lib which one do you mean?

**Comment by djaus2** [comment]
https://github.com/Seeed-Studio/AzureGroveKit/blob/master/UWP/AzureGroveKit/Lib/GrovePi.dll

**Comment by djaus2** [comment]
https://github.com/Seeed-Studio/AzureGroveKit/tree/master/UWP/AzureGroveKit/Lib/grove.dll

ok I take it is this:

https://github.com/DexterInd/GrovePi/tree/master/Software/CSharp

**Comment by awong1900** [comment]
Yes, you got right link.

**Comment by djaus2** [comment]
Thx
